package com.futela.api.application.usecase.category;

import com.futela.api.application.dto.request.category.CreateCategoryRequest;
import com.futela.api.application.dto.request.category.UpdateCategoryRequest;
import com.futela.api.application.dto.response.category.CategoryResponse;
import com.futela.api.domain.exception.ResourceNotFoundException;
import com.futela.api.domain.model.property.Category;
import com.futela.api.domain.port.out.property.CategoryRepositoryPort;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.time.Instant;
import java.util.List;
import java.util.Optional;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class CategoryUseCaseServiceTest {

    @Mock
    private CategoryRepositoryPort categoryRepository;

    @InjectMocks
    private CategoryUseCaseService service;

    private UUID companyId;
    private UUID categoryId;

    @BeforeEach
    void setUp() {
        companyId = UUID.randomUUID();
        categoryId = UUID.randomUUID();
    }

    @Test
    @DisplayName("Doit creer une categorie avec un slug auto-genere")
    void shouldCreateCategoryWithAutoGeneratedSlug() {
        var request = new CreateCategoryRequest("Appartement", "Location d'appartements", "apartment-icon");

        when(categoryRepository.save(any(Category.class))).thenAnswer(invocation -> {
            Category cat = invocation.getArgument(0);
            return new Category(categoryId, cat.name(), cat.slug(), cat.description(),
                    cat.icon(), cat.isActive(), cat.companyId(), cat.createdAt(), cat.updatedAt());
        });

        CategoryResponse response = service.createCategory(request, companyId);

        assertThat(response).isNotNull();
        assertThat(response.id()).isEqualTo(categoryId);
        assertThat(response.name()).isEqualTo("Appartement");

        ArgumentCaptor<Category> captor = ArgumentCaptor.forClass(Category.class);
        verify(categoryRepository).save(captor.capture());
        Category savedCategory = captor.getValue();
        assertThat(savedCategory.slug()).startsWith("appartement-");
        assertThat(savedCategory.companyId()).isEqualTo(companyId);
    }

    @Test
    @DisplayName("Doit retourner la liste des categories par entreprise")
    void shouldReturnCategoriesByCompany() {
        var cat1 = new Category(UUID.randomUUID(), "Appartement", "appartement-abc123",
                "Desc", "icon1", true, companyId, Instant.now(), Instant.now());
        var cat2 = new Category(UUID.randomUUID(), "Maison", "maison-def456",
                "Desc", "icon2", true, companyId, Instant.now(), Instant.now());

        when(categoryRepository.findAllByCompanyId(companyId)).thenReturn(List.of(cat1, cat2));

        List<CategoryResponse> result = service.getCategories(companyId);

        assertThat(result).hasSize(2);
        assertThat(result.get(0).name()).isEqualTo("Appartement");
        assertThat(result.get(1).name()).isEqualTo("Maison");
    }

    @Test
    @DisplayName("Doit mettre a jour une categorie avec succes")
    void shouldUpdateCategorySuccessfully() {
        var existing = new Category(categoryId, "Appartement", "appartement-abc123",
                "Ancienne desc", "old-icon", true, companyId, Instant.now(), Instant.now());
        var request = new UpdateCategoryRequest("Appartement Luxe", "Nouvelle desc", "new-icon");

        when(categoryRepository.findById(categoryId)).thenReturn(Optional.of(existing));
        when(categoryRepository.save(any(Category.class))).thenAnswer(invocation -> invocation.getArgument(0));

        CategoryResponse response = service.updateCategory(categoryId, request);

        assertThat(response).isNotNull();
        assertThat(response.name()).isEqualTo("Appartement Luxe");
        assertThat(response.slug()).isEqualTo("appartement-abc123");
        assertThat(response.description()).isEqualTo("Nouvelle desc");
    }

    @Test
    @DisplayName("Doit rejeter la mise a jour d'une categorie inexistante")
    void shouldRejectUpdateNonExistentCategory() {
        var request = new UpdateCategoryRequest("Nom", "Desc", "icon");

        when(categoryRepository.findById(categoryId)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> service.updateCategory(categoryId, request))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessageContaining("Catégorie");
    }

    @Test
    @DisplayName("Doit retourner une categorie par son identifiant")
    void shouldReturnCategoryById() {
        var category = new Category(categoryId, "Appartement", "appartement-abc123",
                "Desc", "icon", true, companyId, Instant.now(), Instant.now());

        when(categoryRepository.findById(categoryId)).thenReturn(Optional.of(category));

        CategoryResponse response = service.getCategoryById(categoryId);

        assertThat(response).isNotNull();
        assertThat(response.id()).isEqualTo(categoryId);
        assertThat(response.name()).isEqualTo("Appartement");
    }

    @Test
    @DisplayName("Doit rejeter la consultation d'une categorie inexistante")
    void shouldRejectGetNonExistentCategory() {
        when(categoryRepository.findById(categoryId)).thenReturn(Optional.empty());

        assertThatThrownBy(() -> service.getCategoryById(categoryId))
                .isInstanceOf(ResourceNotFoundException.class)
                .hasMessageContaining("Catégorie");
    }
}
